name: Build Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_suffix: ""
          - os: windows-latest
            platform: windows
            artifact_suffix: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev \
          libglib2.0-0 \
          libxkbcommon-x11-0 \
          libdbus-1-3 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xkb1 \
          libxkbcommon-x11-0 \
          libfreetype6-dev \
          libpng-dev \
          libjpeg-dev \
          libtiff-dev \
          libopenjp2-7-dev \
          libgif-dev \
          libwebp-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libxft-dev \
          libfontconfig1-dev \
          libblas-dev \
          liblapack-dev \
          libatlas-base-dev \
          gfortran
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get version (Linux)
      if: runner.os == 'Linux'
      id: get_version_linux
      run: |
        VERSION=$(poetry version -s)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Get version (Windows)
      if: runner.os == 'Windows'
      id: get_version_windows
      shell: pwsh
      run: |
        $VERSION = poetry version -s
        echo "version=$VERSION" >> $env:GITHUB_OUTPUT
    - name: Build executable (Linux)
      if: runner.os == 'Linux'
      run: |
        poetry run python build.py
    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        PYTHONIOENCODING: utf-8
      run: |
        poetry run python build.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
          name: SerialVoltmeter-v${{ steps.get_version_linux.outputs.version || steps.get_version_windows.outputs.version }}-${{ matrix.platform }}
          path: dist/SerialVoltmeter-v${{ steps.get_version_linux.outputs.version || steps.get_version_windows.outputs.version }}${{ matrix.artifact_suffix }}
